name: Check Markdown Files

on:
  push:
    branches:
      - master   # This will run the action every Sunday at midnight

jobs:
  check-markdown-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get date 1 month ago
        id: get_cutoff_date
        run: |
          echo "CUTOFF_DATE=$(date -d '1 month ago' +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Find outdated Markdown files
        id: find_outdated_files
        run: |
          echo $CUTOFF_DATE
          # Initialize an empty variable to store outdated files
          OUTDATED_FILES=""
          FILES=$(git ls-files '*.md')
          echo $FILES

          echo $(ls -al)
          echo $(git blame --date=short package.json)
        

          
          for file in $FILES; do
            echo "Getting last commit date for $file test $(git log --follow --format="%h %ad" -- package.json)"
            
            # Get the last commit date for the file
            LAST_COMMIT_DATE=$(git log -1 --format="%ad")

            echo "Ankit $LAST_COMMIT_DATE"

            # Print the last commit date
            echo "git log -1 --pretty="format:%ci" package.json"
          done
